package lojasentrega;

/**
 * Importação das classes necessárias para o funcionamento do programa
 *
 * @author Lucas Favaro
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Importa a classe LojasEntrega, onde é feito o código da conexão (o Conector).
 */
import lojasentrega.LojasEntrega;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * PreparedStatement e ResultSet são frameforks do pacote Java.sql e servem
     * para preparar e executar as instruções SQL.
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * metodo onde será feito o Login.
     */
    public void logar() {

        /**
         * Seleciona os dados usuario e senha da tabela tbcontas.
         */
        String sql = "select * from tbcontas where Usuario=? and Senha=?";

        try {
            /**
             * Substitui o ? pelo que foi digitado nas caixas de texto, e checa
             * se esse nome e senha estão cadastrados no banco.
             */
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtusuario.getText());
            pst.setString(2, new String(txtsenha.getPassword()));

            /**
             * Executa a query.
             */
            rs = pst.executeQuery();

            if (rs.next()) {
                /**
                 * Se existir usuario e senha correspondentes, será criado e
                 * exibido o Jframe da tela principal.
                 */
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                this.dispose();
                conexao.close();

            } else {
                /**
                 * se não existir usuario ou senha uma mensagem será mostrada.
                 */
                JOptionPane.showMessageDialog(null, "usuario e/ou senha inválido(s)");
            }
        } catch (Exception e) {
            /**
             * Se a conexão falhar.
             */
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * Inicializa os componentes da tela e realiza a conexão.
     */
    public NewJFrame() {
        initComponents();
        conexao = LojasEntrega.conector();
        System.out.println(conexao);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btmlogin = new javax.swing.JButton();
        txtusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btmlogin.setText("Logar");
        btmlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmloginActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmlogin)
                    .addComponent(jButton1))
                .addGap(90, 90, 90))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botão de login que chama o metodo logar.
     */
    private void btmloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmloginActionPerformed
        logar();
    }//GEN-LAST:event_btmloginActionPerformed
    /**
     * Botão de cadastro que realiza o cadastro.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /**
         * Se a conexão for bem sucedida.
         */
        try {

            Connection con = LojasEntrega.conector();

            if (txtusuario.getText().trim().isEmpty() || txtsenha.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                /**
                 * Insere os valores digitados das caixas de texto no lugar do
                 * ?.
                 */
                String queryCheck = "select * from tbcontas where Usuario=?";
                pst = conexao.prepareStatement(queryCheck);
                pst.setString(1, txtusuario.getText());
                rs = pst.executeQuery();
                String sql = "insert into tbcontas(Usuario, Senha) values (?,?)";

                if (rs.next()) {

                    /**
                     * Se existir usuario e senha correspondentes, será exibido
                     * uma mensagem.
                     */
                    JOptionPane.showMessageDialog(null, "Usuário já está Cadastrado!");

                } else {

                    
                    PreparedStatement stmt = conexao.prepareStatement(sql);
                    
                 
                    /**
                     * Insere os valores no banco de dados.
                     */
                    stmt.setString(1, txtusuario.getText());
                    stmt.setString(2, new String(txtsenha.getPassword()));
                    stmt.execute();
                    stmt.close();

                    /**
                     * Mostra uma mensagem quando um usuario é cadastrado.
                     */
                    JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso!");

                    /**
                     * Após cadastrar, remove os valores das caixas de texto,
                     * possibilitando outro cadastro.
                     */
                    txtusuario.setText("");
                    txtsenha.setText("");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
